language: go

go:
  - 1.3
  - tip

install:
  - git submodule update --init --recursive
  - make ci
  - export LD_LIBRARY_PATH="./drafter/build/out/Release/$(if [ $(uname) != "Darwin" ]; then echo 'lib.target/'; fi)"

script:
  - make test
  - go test -v ./...
